# Copyright (C) 2020-2026 Aditya Shakya <adi1090x@gmail.com>
#
# Hyprland configuration : Window Rules --------------------

# You can set window rules to achieve different window behaviors based on their properties.
#
# Syntax: windowrule=RULE,PARAMETERS
#
# RULE is a rule (and a param if applicable)
# PARAMETERS is a comma-separated list of various window attributes you can match by.

# Floating apps
windowrule {
	name = floating terminals
	match:class = foot-float|alacritty-float|kitty-float

	float = on
}

windowrule = match:class yad|nm-connection-editor|org.pulseaudio.pavucontrol, float on
windowrule = match:class xfce-polkit|kvantummanager|qt5ct|qt6ct, float on
windowrule = match:class feh|viewnior|gimp|MPlayer, float on
windowrule = match:class VirtualBox Manager|qemu|Qemu-system-x86_64, float on
windowrule = match:title File Operation Progress, float on
windowrule = match:title Confirm to replace files, float on

# Thunar's rename window
windowrule = match:class thunar, match:title (Rename .*), float on

# Yad window
windowrule = match:class Yad|yad, float on
windowrule = match:class Yad|yad, size 60% 64%

# Installer windows
windowrule = match:class io.calamares.calamares, float on
windowrule = match:class io.calamares.calamares, center on
windowrule = match:title ^(Archcraft Installer)(.*)$, float on

# Viewnior window
windowrule = match:class viewnior, size 60% 64%
windowrule = match:class viewnior, center on

# Alacritty floating geometry
windowrule = match:class Alacritty|alacritty|alacritty-float, size 785 450

# Fullscreen animations
windowrule = match:class foot-full|alacritty-full|kitty-full, animation slide down
windowrule = match:class wlogout, animation slide up

# ---

# Firefox
windowrule = match:class firefox, workspace 2
windowrule = match:class firefox, match:title (Picture-in-Picture), float on
windowrule = match:class firefox, match:title (Picture-in-Picture), size 50%
windowrule = match:class firefox, match:title (Picture-in-Picture), move 100%-w-40 100%-w-40

# ---

# Layer Rules
#
# Syntax: layerrule = rule, namespace or layerrule = rule, address
layerrule = animation slide, match:namespace rofi
layerrule = animation slide, match:namespace notifications
