# Copyright (C) 2020-2026 Aditya Shakya <adi1090x@gmail.com>
#
# Hyprland configuration : Hyprpaper -----------------------

$wallpaper = ~/.config/hyprcat/wallpapers/wallpaper.png

wallpaper {
    monitor = 
    path = $wallpaper
    fit_mode = cover
}

splash = false
splash_offset = 20
splash_color = 55ffffff
ipc = true
